Update `qh-node-spec.js` to use Jest instead of Jasmine
* Replace `testDom` with `jsdom` setup
* Add `global.document` and `global.window` to avoid `document is not defined` error
* Fix `TypeError: jsdom is not a function` error by updating the `jsdom` import