Update dependencies and testing framework (#47)
* Update dependencies and testing framework

Update dependencies and testing framework, and remove Grunt.

* **Dependencies**: Remove Grunt-related dependencies and add Jest, Playwright, and Uglify-js in `package.json`.
* **Scripts**: Add npm scripts for `copy`, `uglify`, `test`, and `build` in `package.json`.
* **Testing Framework**: Update `tests/qh-node-spec.js` and `tests/qh-tests.js` to use Jest instead of Jasmine.
* **Remove Grunt**: Delete `Gruntfile.js` and `karma-conf.js`.

* Update `qh-tests.js` to use Jest instead of Jasmine

* Add `pressKey` and `QwertyHancock` imports

* Add Jest configuration file

* Specify test environment as 'node'
* Define test match patterns for locating test files

* Update Jest configuration file to use jsdom as the test environment

* Change `testEnvironment` from 'node' to 'jsdom'

* Update `qh-node-spec.js` to use Jest instead of Jasmine

* Replace `testDom` with `jsdom` setup
* Add `global.document` and `global.window` to avoid `document is not defined` error
* Fix `TypeError: jsdom is not a function` error by updating the `jsdom` import

* Passing tests!